
analyzer:
  errors:
    avoid_classes_with_only_static_members: ignore
    prefer_final_parameters: ignore
    close_sinks: ignore
    missing_required_param: error
    missing_return: error
    record_literal_one_positional_no_trailing_comma: error
    collection_methods_unrelated_type: warning
    unrelated_type_equality_checks: warning
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true
  exclude:

# 
linter:
  rules:
    - annotate_overrides
    - avoid_annotating_with_dynamic
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_redundant_argument_values
    - avoid_return_types_on_setters
    - always_declare_return_types
    - avoid_types_as_parameter_names
    - test_types_in_equals
    - avoid_single_cascade_in_expression_statements
    - await_only_futures
    - curly_braces_in_flow_control_structures
    - diagnostic_describe_all_properties
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - hash_and_equals
    - no_duplicate_case_values
    - non_constant_identifier_names
    - null_closures
    - prefer_adjacent_string_concatenation
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_contains
    - prefer_final_fields
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    - prefer_generic_function_type_aliases
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_int_literals
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - prefer_null_aware_operators
    - prefer_relative_imports
    - prefer_single_quotes
    - prefer_spread_collections
    # - slash_for_doc_comments
    - sort_child_properties_last
    - type_init_formals
    - unawaited_futures
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_overrides
    - unnecessary_this
    - use_rethrow_when_possible
    - use_super_parameters
    - always_put_required_named_parameters_first
    - unnecessary_late
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - use_enums
    - use_raw_strings
    - use_string_buffers
    - valid_regexps
    - annotate_redeclares
    - avoid_print
    - close_sinks
    - prefer_final_parameters
    - prefer_foreach
    - type_literal_in_constant_pattern